export const charityFieldOptions = [
  { value: "ein", label: "EIN" },
  { value: "name", label: "Name" },
  { value: "ico", label: "ICO" },
  { value: "street", label: "Street" },
  { value: "city", label: "City" },
  { value: "state", label: "State" },
  { value: "zip", label: "ZIP" },
  { value: "group", label: "Group" },
  { value: "subsection_classification", label: "Subsection & Classification" },
  { value: "deductibility", label: "Deductibility" },
  { value: "foundation", label: "Foundation" },
  { value: "filing_req_code", label: "Filing Requirement Code" },
  { value: "pf_filing_req_code", label: "PF Filing Requirement Code" },
  { value: "account_paid", label: "Account Paid" },
  { value: "ntee_code", label: "NTEE Code" },
  { value: "ntee_group", label: "NTEE Group" },
  { value: "asset_amount", label: "Asset Amount" },
  { value: "income_amount", label: "Income Amount" },
  { value: "revenue_amount", label: "Revenue Amount" },
  { value: "ruling", label: "Ruling" },
  { value: "tax_period", label: "Tax Period" },
  { value: "organization", label: "Organization" },
  { value: "status", label: "Status" },
  { value: "affiliation", label: "Affiliation" },
];